# Generated by Django 5.0.4 on 2024-04-25 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinaccount",
            name="last_used",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 25, 0, 8, 3, 339226, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last used",
            ),
            preserve_default=False,
        ),
    ]
