# Generated by Django 5.0.4 on 2024-04-24 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "universal_name",
                    models.CharField(max_length=256, verbose_name="universal name"),
                ),
                (
                    "linkedin_id",
                    models.CharField(max_length=32, verbose_name="linkedin ID"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/", verbose_name="logo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                (
                    "linkedin_geo_id",
                    models.CharField(max_length=32, verbose_name="linkedin geo ID"),
                ),
                (
                    "flag_emoji",
                    models.CharField(max_length=8, verbose_name="flag emoji"),
                ),
                (
                    "flag_image",
                    models.ImageField(
                        upload_to="job/locations/flags", verbose_name="flag image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                (
                    "linkedin_id",
                    models.CharField(max_length=32, verbose_name="linkedin ID"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "linkedin_id",
                    models.CharField(max_length=32, verbose_name="linkedin ID"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                ("attributes", models.JSONField(verbose_name="attributes")),
                (
                    "full_location",
                    models.CharField(max_length=128, verbose_name="full location"),
                ),
                ("listed_at", models.DateTimeField(verbose_name="listed at")),
                ("on_site", models.BooleanField(default=False, verbose_name="on-site")),
                ("hybrid", models.BooleanField(default=False, verbose_name="hybrid")),
                ("remote", models.BooleanField(verbose_name="remote")),
                (
                    "full_time",
                    models.BooleanField(default=False, verbose_name="full_time"),
                ),
                (
                    "part_time",
                    models.BooleanField(default=False, verbose_name="part_time"),
                ),
                (
                    "contract",
                    models.BooleanField(default=False, verbose_name="contract"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT_FOR_REVIEW", "Waiting For Review"),
                            ("LISTED", "Listed"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="job.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="job.joblocation",
                        verbose_name="location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
            },
        ),
    ]
