# Generated by Django 5.0.4 on 2024-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="attributes",
            field=models.JSONField(blank=True, default=dict, verbose_name="attributes"),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="job",
            name="full_location",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="full location"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="listed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="listed at"),
        ),
        migrations.AlterField(
            model_name="job",
            name="remote",
            field=models.BooleanField(default=False, verbose_name="remote"),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PARTIALLY_PROCEEDED", "Partially Proceeded"),
                    ("WAIT_FOR_REVIEW", "Waiting For Review"),
                    ("LISTED", "Listed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="PARTIALLY_PROCEEDED",
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
