# Generated by Django 5.0.4 on 2024-04-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_job_attributes_alter_job_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joblocation",
            options={
                "verbose_name": "Job Location",
                "verbose_name_plural": "Job Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="jobtitle",
            options={"verbose_name": "Job Title", "verbose_name_plural": "Job Titles"},
        ),
        migrations.AddField(
            model_name="job",
            name="job_titles",
            field=models.ManyToManyField(to="job.jobtitle", verbose_name="job titles"),
        ),
    ]
