# Generated by Django 5.0.4 on 2024-04-25 09:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_joblocation_options_alter_jobtitle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblocation",
            name="iso_code",
            field=models.CharField(
                default="iso", max_length=4, verbose_name="ISO code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="job_titles",
            field=models.ManyToManyField(
                related_name="jobs", to="job.jobtitle", verbose_name="job titles"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PARTIALLY_PROCEEDED", "Partially Proceeded"),
                    ("FULLY_PROCEEDED", "Fully Proceeded"),
                    ("WAIT_FOR_REVIEW", "Waiting For Review"),
                    ("LISTED", "Listed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="PARTIALLY_PROCEEDED",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="joblocation",
            name="flag_image",
            field=models.ImageField(
                upload_to=core.models.ImageFieldRename(
                    "job/locations/flags", "iso_code"
                ),
                verbose_name="flag image",
            ),
        ),
    ]
