# Generated by Django 5.0.4 on 2024-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_joblocation_iso_code_alter_job_job_titles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description_include_keywords",
            field=models.BooleanField(
                default=False, verbose_name="description include keywords"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="found_via_search_keywords",
            field=models.BooleanField(
                default=False, verbose_name="found via search keywords"
            ),
        ),
    ]
