# Generated by Django 5.0.4 on 2024-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_remove_job_description_include_keywords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "linkedin_id",
                    models.CharField(max_length=32, verbose_name="linkedin ID"),
                ),
            ],
            options={
                "verbose_name": "Job Skill",
                "verbose_name_plural": "Job Skills",
            },
        ),
        migrations.AddField(
            model_name="job",
            name="job_skills",
            field=models.ManyToManyField(
                related_name="jobs", to="job.jobskill", verbose_name="job skills"
            ),
        ),
    ]
